databaseChangeLog:
  - changeSet:
      id: 2-trainer-insert-sample
      author: haider
      changes:
        - insert:
            tableName: trainer
            columns:
              - column:
                  name: username
                  value: trainer1
              - column:
                  name: password
                  value: '$2a$12$VySF0eTFX7x8IVogowpeLepgRkaQXbdke4hPtK5CYn.RxXy.LPPsG'
              - column:
                  name: phone_number
                  value: '0987654321'
              - column:
                  name: specialty
                  value: Strength Training
              - column:
                  name: salary
                  valueNumeric: 40000.00
              - column:
                  name: role
                  value: TRAINER
